/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Koneksi.Connect;
import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class Form_Pelanggan extends javax.swing.JFrame {

    /**
     */
    public boolean addNew;
    public int row;
    
    public Form_Pelanggan() {
        initComponents();
        row = 0;
        loadData();
    }
    public void loadData(){
    DefaultTableModel models=new DefaultTableModel();
    models.addColumn("Kode");
    models.addColumn("Nama Pelanggan");
    models.addColumn("Nomor HP");

    
    try {
        Statement statement=(Statement)Connect.GetConnection().createStatement();
        ResultSet res=statement.executeQuery("select * from pelanggan");
        while(res.next())
    {
       models.addRow(new Object[]{
        res.getString("kode_pelanggan"),
        res.getString("nama_pelanggan"),
        res.getString("nomor_pelanggan"),
        });
       tabel2.setModel(models);
        }
        }catch (Exception e){
        JOptionPane.showMessageDialog(rootPane,"Tidak Ada Data");
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tabel2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nomor_pelanggan = new javax.swing.JTextField();
        nama_pelanggan = new javax.swing.JTextField();
        edit = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabel2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel2);

        jLabel1.setText("Form Pelanggan");

        jLabel2.setText("Nama Pelanggan :");

        jLabel3.setText("Nomor Pelanggan :");

        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        tambah.setText("Tambah");
        tambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tambahMouseClicked(evt);
            }
        });
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });

        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(edit))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tambah)
                        .addGap(18, 18, 18)
                        .addComponent(simpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                        .addComponent(hapus))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nama_pelanggan)
                            .addComponent(nomor_pelanggan)))
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator3))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(edit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nama_pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nomor_pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambah)
                    .addComponent(simpan)
                    .addComponent(hapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        addNew = false;
    }//GEN-LAST:event_editActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        String nama = nama_pelanggan.getText();
        String nomor = nomor_pelanggan.getText();
        String kode = (String)tabel2.getValueAt(row, 0);
        if (addNew == true) {
            if("".equals(nama) || "".equals(nomor)){
                JOptionPane.showMessageDialog(null, "Harap Isi Semua Data!");
            } else{
                try{
                    Statement stm = (Statement) Connect.GetConnection().createStatement();
                    stm.execute("INSERT into pelanggan VALUES (null,'" + nama_pelanggan.getText() + "','" + nomor_pelanggan.getText() + "');");
                    stm.close();
                    JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan!","SIMPAN DATA",JOptionPane.INFORMATION_MESSAGE);
                } catch (Exception t){
                    JOptionPane.showMessageDialog(null, "Data Gagal Disimpan!","SIMPAN DATA",JOptionPane.INFORMATION_MESSAGE);
                }
                loadData();
                }
                }else{
                    try{
                        Statement stm = (Statement) Connect.GetConnection().createStatement();
                        stm.execute("UPDATE pelanggan SET " + "nama_pelanggan = '" + nama + "'," + "nomor_pelanggan = '" + nomor + "' " + "WHERE kode_pelanggan = " + kode + ";");
                        stm.close();
                        JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan!","SIMPAN DATA",JOptionPane.INFORMATION_MESSAGE);
                    } catch (Exception t){
                        JOptionPane.showMessageDialog(null, "Data Gagal Disimpan!","SIMPAN DATA",JOptionPane.INFORMATION_MESSAGE);
                    }
                    loadData();
    }//GEN-LAST:event_simpanActionPerformed
    }
    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        String kode = (String)tabel2.getValueAt(row, 0);

        int Pilih = JOptionPane.showConfirmDialog(null,"Anda Yakin Data Akan Dihapus??","HAPUS DATA",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
        if(Pilih == JOptionPane.YES_OPTION){
        try{
            Statement stm = (Statement) Connect.GetConnection().createStatement();
            stm.execute("DELETE from pelanggan WHERE kode_pelanggan = '" + kode + "';");
            stm.close();
            JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus!");
        } catch (Exception t){
            JOptionPane.showMessageDialog(null, "Data Gagal Dihapus!");
        }
        loadData();
        row = 0;
        } else if(Pilih == JOptionPane.NO_OPTION){
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void tambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambahMouseClicked
        // TODO add your handling code here:
         
    }//GEN-LAST:event_tambahMouseClicked

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
        textKosong();
        addNew=true;
    }//GEN-LAST:event_tambahActionPerformed
    public void textKosong(){
    nama_pelanggan.setText("");
    nomor_pelanggan.setText("");
    }
    private void tabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel2MouseClicked
        // TODO add your handling code here:
        setRowTbl();
        setField();
    }//GEN-LAST:event_tabel2MouseClicked
    public void setRowTbl(){
    row = tabel2.getSelectedRow();
    }
    public void setField(){
    nama_pelanggan.setText((String)tabel2.getValueAt(row,1));
    nomor_pelanggan.setText((String)tabel2.getValueAt(row,2));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Pelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton edit;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField nama_pelanggan;
    private javax.swing.JTextField nomor_pelanggan;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tabel2;
    private javax.swing.JButton tambah;
    // End of variables declaration//GEN-END:variables
}
